# Generated by Django 4.0 on 2021-12-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
