# Generated by Django 4.0 on 2021-12-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0005_alter_userwantrequest_from_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwantrequest",
            name="status_request",
            field=models.CharField(
                choices=[("initiated", "initiated"), ("received", "received")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userwantrequest",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="from_user_received",
                to="api_app.user",
            ),
        ),
        migrations.AlterField(
            model_name="userwantrequest",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="to_user_sent",
                to="api_app.user",
            ),
        ),
    ]
