# Generated by Django 4.0 on 2021-12-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0007_documentrequest_remove_userprofile_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="status_request",
            field=models.PositiveSmallIntegerField(
                choices=[
                    ("INITIATED_STATUS", "initiated"),
                    ("RECEIVED_STATUS", "received"),
                ],
                default=1,
            ),
        ),
    ]
