# Generated by Django 4.0 on 2021-12-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0008_alter_documentrequest_status_request"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentrequest",
            name="status_request",
        ),
    ]
