# Generated by Django 4.0 on 2021-12-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0012_alter_documentrequest_status_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="status_request",
            field=models.PositiveIntegerField(
                choices=[
                    ("INITIATED_STATUS", "initiated"),
                    ("RECEIVED_STATUS", "received"),
                ]
            ),
        ),
    ]
