# Generated by Django 4.0 on 2021-12-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0014_alter_documentrequest_status_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrequest",
            name="status_request",
            field=models.CharField(
                choices=[(1, "initiated"), (2, "received")], max_length=50
            ),
        ),
    ]
