# Generated by Django 4.0 on 2021-12-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_alter_documentrequest_status_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status_request',
            field=models.PositiveSmallIntegerField(choices=[(1, 'initiated'), (2, 'received')], default=1),
        ),
    ]
